export const ComponentIDs = {
  addProjectMenuItem: 'addProjectMenuItem',
  addProjectFormName: 'addProjectFormName',
  addProjectFormPicture: 'addProjectFormPicture',
  addProjectFormHomePage: 'addProjectFormHomePage',
  addProjectFormDescription: 'addProjectFormDescription',
  addProjectFormInterests: 'addProjectFormInterests',
  addProjectFormParticipants: 'addProjectFormParticipants',
  addProjectFormSubmit: 'addProjectFormSubmit',
  basicNavbarNav: 'basicNavbarNav',
  currentUserDropdown: 'currentUserDropdown',
  currentUserDropdownSignOut: 'currentUserDropdownSignOut',
  filterFormInterests: 'filterFormInterests',
  filterFormSubmit: 'filterFormSubmit',
  filterMenuItem: 'filterMenuItem',
  homeFormFirstName: 'homeFormFirstName',
  homeFormLastName: 'homeFormLastName',
  homeFormBio: 'homeFormBio',
  homeFormSubmit: 'homeFormSubmit',
  homeMenuItem: 'homeMenuItem',

  sessionCourse: 'sessionCourse',
  sessionTime: 'sessionTime',
  sessionMonth: 'sessionMonth',
  sessionDay: 'sessionDay',
  sessionYear: 'sessionYear',
  sessionSubmit: 'sessionSubmit',

  interestsMenuItem: 'interestsMenuItem',
  loginDropdown: 'loginDropdown',
  loginDropdownSignIn: 'loginDropdownSignIn',
  loginDropdownSignUp: 'loginDropdownSignUp',
  profilesMenuItem: 'profilesMenuItem',
  projectsMenuItem: 'projectsMenuItem',
  signInFormEmail: 'signInFormEmail',
  signInFormPassword: 'signInFormPassword',
  signInFormSubmit: 'signInFormSubmit',
  signUpFormEmail: 'signUpFormEmail',
  signUpFormPassword: 'signUpFormPassword',
  signUpFormSubmit: 'signUpFormSubmit',
  yourProfileMenuItem: 'yourProfileMenuItem',
  yourProfileFormFirstName: 'yourProfileFormFirstName',
  yourProfileFormLastName: 'yourProfileFormLastName',
  yourProfileFormBio: 'yourProfileFormBio',
  yourProfileFormSubmit: 'yourProfileFormSubmit',
};

export const PageIDs = {
  addProjectPage: 'addProjectPage',
  filterPage: 'filterPage',
  homePage: 'homePage',
  interestsPage: 'interestsPage',
  landingPage: 'landingPage',
  notAuthorizedPage: 'notAuthorizedPage',
  notFoundPage: 'notFoundPage',
  profilesPage: 'profilesPage',
  projectsPage: 'projectsPage',
  signInPage: 'signInPage',
  signOutPage: 'signOutPage',
  signUpPage: 'signUpPage',
  yourProfilePage: 'yourProfilePage',
};
